
import ProviderStore from "@/store";
import "./globals.css";
import { Inter } from "next/font/google";
import DefaultLayout from "@/layout/defaultlayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Hotel app",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProviderStore>
                    <DefaultLayout>
                        <div className="my-4"> {children}</div>
                    </DefaultLayout>
                </ProviderStore>
            </body>
        </html>
    );
}
